version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: caycanh-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: caycanh-web
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
